# Generated by Django 4.1.1 on 2022-11-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='魚種')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='写真')),
                ('capital', models.TextField(blank=True, null=True, verbose_name='都道府県')),
                ('city', models.TextField(blank=True, null=True, verbose_name='市区町村')),
                ('address', models.TextField(blank=True, null=True, verbose_name='番地以降')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='番地以降')),
                ('place', models.TextField(blank=True, null=True, verbose_name='場所')),
                ('location', models.TextField(blank=True, choices=[('海', '海'), ('川', '川'), ('管理釣り場', '管理釣り場'), ('船', '船'), ('湖', '湖'), ('その他', 'その他')], null=True, verbose_name='ロケーション')),
                ('free', models.TextField(blank=True, null=True, verbose_name='自由記入欄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.TextField(blank=True, choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], verbose_name='都道府県')),
                ('city', models.TextField(blank=True, verbose_name='市区町村')),
                ('address', models.TextField(blank=True, verbose_name='番地以降')),
                ('place', models.TextField(blank=True, verbose_name='場所')),
                ('location', models.TextField(blank=True, verbose_name='ロケーション')),
                ('fish', models.TextField(blank=True, null=True, verbose_name='釣れる魚')),
                ('spotURL', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('free', models.TextField(blank=True, null=True, verbose_name='自由記入欄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
