# Generated by Django 3.2.7 on 2022-11-21 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.CharField(blank=True, choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], max_length=5, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='市区町村')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='番地以降')),
                ('place', models.CharField(blank=True, max_length=20, null=True, verbose_name='場所')),
                ('location', models.CharField(blank=True, choices=[('海', '海'), ('川', '川'), ('管理釣り場', '管理釣り場'), ('船', '船'), ('湖', '湖'), ('その他', 'その他')], max_length=5, null=True, verbose_name='ロケーション')),
                ('free', models.TextField(blank=True, null=True, verbose_name='自由記入欄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Catch',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField(blank=True, null=True, verbose_name='分類')),
                ('title', models.TextField(blank=True, null=True, verbose_name='タイトル')),
                ('shopphoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='お店の写真')),
                ('shopURL', models.URLField(blank=True, null=True, verbose_name='お店のURL')),
                ('iinecount', models.TextField(blank=True, null=True, verbose_name='いいね総数')),
                ('URLcheck', models.TextField(blank=True, null=True, verbose_name='URL確認チェック')),
                ('titlephoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='タイトル写真')),
                ('titlemovie', models.TextField(blank=True, null=True, verbose_name='タイトル動画')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.TextField(blank=True, choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], verbose_name='都道府県')),
                ('city', models.TextField(blank=True, verbose_name='市区町村')),
                ('address', models.TextField(blank=True, verbose_name='番地以降')),
                ('place', models.TextField(blank=True, verbose_name='釣り場名')),
                ('location', models.TextField(blank=True, verbose_name='ロケーション')),
                ('spotURL', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('URLcheck', models.IntegerField(blank=True, null=True, verbose_name='URLチェック')),
                ('free', models.TextField(blank=True, null=True, verbose_name='自由記入欄')),
                ('beginner', models.BooleanField(blank=True, default=False, help_text='初心者おすすめ', null=True, verbose_name='初心者おすすめチェック')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Spot',
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triviaimg', models.ImageField(blank=True, upload_to='', verbose_name='豆知識画像')),
                ('trivia', models.TextField(blank=True, verbose_name='豆知識')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, verbose_name='順番')),
                ('procedure', models.IntegerField(blank=True, verbose_name='手順')),
                ('photo', models.IntegerField(blank=True, verbose_name='写真')),
                ('material', models.IntegerField(blank=True, verbose_name='材料')),
                ('amount', models.IntegerField(blank=True, verbose_name='量')),
                ('unit', models.IntegerField(blank=True, verbose_name='単位')),
                ('recipeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oniokoze.recipe', verbose_name='レシピID')),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Iine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catchID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oniokoze.catch', verbose_name='釣果ID')),
                ('recipeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oniokoze.recipe', verbose_name='レシピID')),
                ('spotID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oniokoze.spot', verbose_name='釣り場ID')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Fishname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='魚種')),
                ('size', models.IntegerField(blank=True, verbose_name='サイズ')),
                ('No', models.IntegerField(blank=True, verbose_name='種類数')),
                ('catchID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oniokoze.catch', verbose_name='釣果ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.IntegerField(blank=True, verbose_name='釣れる魚')),
                ('No', models.IntegerField(blank=True, verbose_name='番号')),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oniokoze.spot', verbose_name='釣り場ID')),
            ],
        ),
    ]
