# Generated by Django 3.2.7 on 2023-02-03 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oniokoze', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='spotfish',
        ),
        migrations.AlterField(
            model_name='order',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='oniokoze.recipe'),
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.TextField(blank=True, null=True, verbose_name='釣れる魚')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='番号')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oniokoze.spot')),
            ],
            options={
                'verbose_name_plural': 'Fish',
            },
        ),
    ]
