# Generated by Django 3.2.7 on 2023-01-23 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oniokoze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeForPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Catchlike',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='check',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='order',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipelike',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='changeID',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='fish',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='spotlike',
        ),
        migrations.AddField(
            model_name='spot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='spotfish',
            field=models.TextField(blank=True, verbose_name='釣れる魚'),
        ),
        migrations.AddField(
            model_name='spot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='spot',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser', verbose_name='ユーザー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(blank=True, choices=[('調理', '調理'), ('処理', '処理'), ('豆知識', '豆知識')], verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='location',
            field=models.CharField(blank=True, choices=[('海', '海'), ('川', '川'), ('管理釣り場', '管理釣り場'), ('船', '船'), ('湖', '湖'), ('その他', 'その他')], max_length=5, null=True, verbose_name='ロケーション'),
        ),
        migrations.DeleteModel(
            name='Recipelike',
        ),
        migrations.DeleteModel(
            name='Spotlike',
        ),
        migrations.AddField(
            model_name='likeforpost',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oniokoze.spot'),
        ),
        migrations.AddField(
            model_name='likeforpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
