# Generated by Django 3.2.7 on 2022-11-07 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oniokoze', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='size',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='fish',
        ),
        migrations.AddField(
            model_name='catch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser', verbose_name='ユーザーID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='URLcheck',
            field=models.IntegerField(blank=True, null=True, verbose_name='URLチェック'),
        ),
        migrations.AddField(
            model_name='spot',
            name='beginner',
            field=models.BooleanField(blank=True, default=False, help_text='初心者おすすめ', null=True, verbose_name='初心者おすすめチェック'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='place',
            field=models.TextField(blank=True, verbose_name='釣り場名'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField(blank=True, null=True, verbose_name='分類')),
                ('title', models.TextField(blank=True, null=True, verbose_name='タイトル')),
                ('shopphoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='お店の写真')),
                ('shopURL', models.URLField(blank=True, null=True, verbose_name='お店のURL')),
                ('iinecount', models.TextField(blank=True, null=True, verbose_name='いいね総数')),
                ('URLcheck', models.TextField(blank=True, null=True, verbose_name='URL確認チェック')),
                ('titlephoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='タイトル写真')),
                ('titlemovie', models.TextField(blank=True, null=True, verbose_name='タイトル動画')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, verbose_name='順番')),
                ('procedure', models.IntegerField(blank=True, verbose_name='手順')),
                ('photo', models.IntegerField(blank=True, verbose_name='写真')),
                ('material', models.IntegerField(blank=True, verbose_name='材料')),
                ('amount', models.IntegerField(blank=True, verbose_name='量')),
                ('unit', models.IntegerField(blank=True, verbose_name='単位')),
                ('recipeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oniokoze.recipe', verbose_name='レシピID')),
            ],
        ),
    ]
