# Generated by Django 3.2.7 on 2023-02-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oniokoze', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Spotlike'},
        ),
        migrations.AlterField(
            model_name='fishname',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='サイズ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='量'),
        ),
    ]
