# Generated by Django 3.2.7 on 2023-02-07 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oniokoze', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Spotlike'},
        ),
        migrations.RemoveField(
            model_name='spot',
            name='spotfish',
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser', verbose_name='ユーザー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fish',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish', to='oniokoze.spot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='oniokoze.recipe'),
        ),
    ]
