# Generated by Django 3.2.7 on 2023-02-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oniokoze', '0002_auto_20230203_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Spotlike'},
        ),
    ]
