# Generated by Django 3.2.7 on 2023-01-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oniokoze', '0002_auto_20230123_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='userID',
        ),
    ]
