# Generated by Django 3.2.7 on 2023-02-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oniokoze', '0002_auto_20230208_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishname',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='サイズ'),
        ),
    ]
