# Generated by Django 3.2.7 on 2023-01-25 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oniokoze', '0003_remove_recipe_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeForPost',
            new_name='LikeForCatch',
        ),
        migrations.AlterField(
            model_name='fishname',
            name='catch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishname', to='oniokoze.catch'),
        ),
        migrations.AlterField(
            model_name='likeforcatch',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oniokoze.catch'),
        ),
        migrations.CreateModel(
            name='LikeForSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oniokoze.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeForRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oniokoze.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
