# Generated by Django 3.2.7 on 2023-01-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oniokoze', '0004_auto_20230125_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={'verbose_name_plural': 'Fish'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Fishname'},
        ),
        migrations.AddField(
            model_name='fish',
            name='spot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oniokoze.spot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='oniokoze.recipe'),
            preserve_default=False,
        ),
    ]
